config/routes.rb
Rails.application.routes.draw do
	root 'home#index'

	#user
	patch 'user/:id/edit/password'=> 'users#update_password', :as => 'alterar_senha'
	get 'users/:id/delete', to: 'users#destroy', :as => 'delete_user'
	get 'users' => 'users#index', :as => 'users'
	post 'users' => 'users#index', :as => 'users_post'
	post 'users/create' => 'users#create', :as => 'users_create'

	#sessions
	get    'login'   => 'sessions#new'
	post   'login'   => 'sessions#create'
	get 'logout', to: 'sessions#destroy', :as => 'logout'

	#books
	get 'books' => 'books#index', :as => 'books'
	post 'books' => 'books#index', :as => 'books_post'
	post 'books/create' => 'books#create', :as => 'books_create'
	get 'books/:id/delete', to: 'books#destroy', :as => 'delete_book'

	#loans
	get 'loans/create/:id' => 'loans#create', :as => 'loans_create'
	get 'loans/return_book/:id' => 'loans#return_book', :as => 'loans_return_book'
	get 'loans' => 'loans#index', :as => 'loans'

	#schedules
	get 'schedules/create/:id' => 'schedules#create', :as => 'schedules_create'
	get 'schedules' => 'schedules#index', :as => 'schedules'
	get 'schedule/:id/delete', to: 'schedules#destroy', :as => 'delete_schedule'


	resources :books, except:[:index, :create]
	resources :users, except:[:index, :create]
	resources :sessions
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :email_confirmation, :older_password
	has_many :schedules, :dependent => :destroy
	has_many :loans, :dependent => :destroy
	
	#Bcrypt encrypt
    has_secure_password :validations => false

	#name
    validates_length_of :name,
				  		:within => 3..50,
				  		:too_short => "Nome tem que ter no mínimo 3 caracteres",
				  		:too_long => "Nome tem que ter no máximo 50 caracteres"
    validates :name, :presence => { message: "Nome Completo não pode ser vazio" }


	#email
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, :uniqueness => { message:"Este e-mail já está em uso"},
            :presence => { message: "E-mail não pode ser vazio" },
	          length: { maximum: 50},
	          format: { with: VALID_EMAIL_REGEX, message: "Insira um e-mail válido"}, 
	          on: :create

	#password
    validates_length_of :password,
			            :within => 6..15,
			            :too_short => 'Senha tem que ter no mínimo 6 caracteres',
			            :too_long => 'Senha tem que ter no máximo 15 caracteres',
			            on: :create

	#mobile phone
	validates :telefone, :numericality => {:message => 'Telefone deve ter somente números e sem espaços'}
	validates_length_of :telefone,
				  		:within => 11..15,
				  		:too_short => 'Telefone tem que ter no mínimo 11 caracteres!',
				  		:too_long => 'Telefone tem que ter no máximo 15 caracteres!'

	#cpf
	validates_length_of :cpf, :is => 11 , :message => 'CPF inválido'
	validates_numericality_of :cpf, :message => 'CPF deve possuir apenas números'
	validates :cpf, :uniqueness => {message: "Este CPF já está sendo usado"}
    validates :cpf, :presence => { message: "CPF não pode ser vazio" }


	#matricula
	validates_numericality_of :matricula, :message => 'Matrícula deve possuir apenas números'
	validates :matricula, :uniqueness => {message: "Esta matrícula já está sendo usada"}
    validates :matricula, :presence => { message: "Matrícula não pode ser vazia" }


	#numero
	validates_numericality_of :numero, :message => 'Número deve possuir apenas números'

	#CEP
	validates_numericality_of :cep, :message => 'CEP deve possuir apenas números'
	validates_length_of :cep, :is => 8 , :message => 'CEP inválido'

	#Endereço
	validates_length_of :endereco,
				  		:within => 3..50,
				  		:too_short => "Endereço tem que ter no mínimo 3 caracteres",
				  		:too_long => "Endereço tem que ter no máximo 50 caracteres"

	#complemento
	validates :complemento, length: { maximum: 20, message: "Complemento deve ter no máximo 20 caracteres" }

	#Data Nascimento
	validates :dataNascimento, :presence => {:message => 'Data de Nascimento não pode ser vazia'}

	#password_confirmation
	validates_confirmation_of :password, :message => "As senhas devem ser iguais na confirmação"

    #email_confirmation
	validates_confirmation_of :email, :message => "Os e-mails devem ser iguais na confirmação",
	                                  on: :create

	#older_password
	validates :older_password, length: {minimum: 6,
                               	        message: 'Senha antiga deve possuir no mínimo 6 caracteres'},
                               on: :update_password

    include PgSearch
	pg_search_scope :search_full_text, 
	                :against => [:name, :cpf, :email, :matricula], 
	                :using => { 
			                	:tsearch => {:prefix => true, :any_word => true}
			                   }
	has_many :loans, :dependent => :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :autorized_user, :except => [:new, :create]
	before_action :set_user, only: [:show, :update, :destroy, :edit, :update_password]
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to login_path
			flash[:success] = "Usuário criado com sucesso"
		else
			render :new
		end
	end

	def show
		unless current_user.id == @user.id || is_admin?
			redirect_to user_path current_user
		end 
	end

	def index
		search_user(params[:users_search])
		@users_search = params[:users_search]
	end 

	def edit
		if current_user != @user
			redirect_to edit_user_path current_user
		else
			unless @user
				flash.now[:warning] = "Não foi encontrar o usuário"
				redirect_to users_path
			end
		end
	end

	def update
		if @user.update(user_params_update)
			flash.now[:success] = "Atualizado com sucesso"
			redirect_to root_path
		else
			render :edit
		end
	end

	def update_password
		if  @user.authenticate(params[:user][:older_password])
			if @user.id == current_user.id
				change_older_password
				flash[:success] = "Senha alterada com sucesso"
			else
				render :edit
				flash.now[:warning] = "Não foi possível atualizar a senha"
			end
		else
			flash.now[:warning] = "Senha antiga incorreta"
			render :edit
		end
	end

	def destroy
		if current_user.id == @user.id || is_admin?
			if @user.destroy
				flash.now[:success] = "Perfil removido com sucesso"
			else
				flash.now[:danger] = "Não foi possível remover seu perfil"
			end
			if is_admin?
				redirect_to users_path
			else
				log_out 
				redirect_to login_path
			end
		end
	end

	private 
	def set_user
		@user = User.find_by_id(params[:id])
	end

	def user_params
		params.require(:user).permit(:name, :cpf, :matricula, :email, :telefone,
			:dataNascimento, :endereco, :numero, 
			:complemento, :cep, :password,
			:password_confirmation,:email_confirmation)
	end

	def user_params_update
		params.require(:user).permit(:name, :cpf, :matricula, :telefone,
			:dataNascimento, :endereco, :numero, 
			:complemento, :cep)
	end

	def params_update_password
        params.require(:user).permit( :older_password, :password, :password_confirmation)
    end

	def change_older_password
		if @user.update_attributes(params_update_password)
			flash[:success] = 'Senha atualizada com sucesso'
			redirect_to root_path
		else
			render :edit
			flash.now[:warning] = 'Não foi possível atualizar a senha'
		end
	end

	def search_user(user_search)
		if is_admin?
			unless user_search.blank?
				@users = User.search_full_text("#{user_search}")
			else
				@users = User.all
			end
		else 
			flash[:warning] = "Você não tem permissão para realizar essa ação"
			redirect_to root_path
		end 
	end
end

app/views/users/edit.html.erb
  <% @user.errors.each do |attr,message| %>
  <div style="padding-top: 50px;">
    <div class="alert alert-warning alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <%= message %>.
    </div>
  </div>
  <%end%>
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Usuários</h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md- col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Atualizar Cadastro de Usuário</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            <%= form_for @user, html:{class:"form-horizontal form-label-left input_mask"} do | f | %>
            <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :name,"Nome Completo*"%>
                <%= f.text_field :name, class: 'form-control', placeholder: 'Nome e Sobrenome', minlength: '3', maxlength: '50', required: ''%>
              </div>
              <div class="col-md-2 col-sm-2 col-xs-12 form-group ">
                <%= f.label :dataNascimento,"Data Nascimento*"%>
                <%= f.date_field :dataNascimento, class: 'form-control', required: ''%>
              </div>
              <div class="col-md-3 col-sm-2 col-xs-12 form-group ">
                <%= f.label :cpf,"CPF*"%>
                <%= f.telephone_field :cpf, class: 'form-control', placeholder: 'Somente números', minlength: '11', maxlength: '11', required: ''%>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3 col-sm-2 col-xs-12 form-group ">
                <%= f.label :matricula,"Matrícula*"%>
                <%= f.text_field :matricula, class: 'form-control', placeholder: 'Somente números', minlength: '3', maxlength: '50', required: ''%>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3 col-sm-4 col-xs-12 form-group ">
                <%= f.label :telefone,"Telefone*"%>
                <%= f.telephone_field :telefone, class: 'form-control',placeholder: 'DDD + número', minlength: '11', maxlength: '11', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :email,"Email*"%>
                <%= f.email_field :email, class: 'form-control', required: '', disabled: true%>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-md-4 col-sm-6 col-xs-12 form-group ">
                <%= f.label :cep,"CEP*"%>
                <%= f.telephone_field :cep, class: 'form-control',minlength: '8', maxlength: '8', required: ''%>
              </div>
            </div>
            <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :endereco,"Endereço*"%>
                <%= f.text_field :endereco, class: 'form-control',minlength: '3', maxlength: '50', required: ''%>
              </div>
              <div class="col-md-3 col-sm-3 col-xs-12 form-group ">
                <%= f.label :numero,"Número*"%>
                <%= f.number_field :numero, class: 'form-control',placeholder: 'Somente números', required: ''%>
              </div>
              <div class="col-md-5 col-sm-5 col-xs-12 form-group ">
                <%= f.label :complemento,"Complemento*"%>
                <%= f.text_field :complemento, class: 'form-control',maxlength: '20', required: ''%>
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="pull-right">
              <div class="btn-block">
                <%= f.submit "Atualizar", class: 'btn btn-success'%>
              </div>
            </div>
            <% end%>

            <div class="x_title">
              <h2>Alterar Senha</h2>
              <div class="clearfix"></div>
            </div>

            <%= form_for @user, url: alterar_senha_path, html: { autocomplete: 'off' } do |f|%>
            <div class="row">
             <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
              <%= f.label :older_password,"Senha Antiga"%>
              <%= f.password_field :older_password, class: 'form-control input-md', placeholder: 'Senha antiga', minlength: '6'%>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
              <%= f.label :password,"Nova Senha*"%>
              <%= f.password_field :password, class: 'form-control',minlength: '6', maxlength: '15', required: ''%>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
              <%= f.label :password_confirmation,"Confirme a nova Senha*"%>
              <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: 'off' , placeholder: 'Confirmação de senha', required: '', minlength: '6', maxlength: '15'%>
            </div>
          </div>
          <hr />
          <div id="actions" class="row">
            <div class="pull-right">

              <div class="col-md-12">
                <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
                
                <%= f.submit "Alterar Senha", class: 'btn btn-success'%>
              </div>
            </div>
          </div>
          <br> </br>
          <% end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Usuários</h3>
        </div>
    </div>
    <%= form_tag users_post_path, method: :post do %>
    <div class="title_right">
        <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <%= text_field_tag :users_search, @users_search, class: "form-control input-md", placeholder: "Nome, CPF, Matrícula, Email..."%>
                <span class="input-group-btn">
                <button class="btn btn-default" type="submit"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                </span>
            </div>
        </div>
    </div>
    <%end%>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md- col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Consulta de usuários</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table width="100%" class="table table-striped table-bordered table-hover table-responsive" id="dataTables-example">
                        <thead>
                            <tr>
                                <th width="25%">Nome</th>
                                <th>CPF</th>
                                <th>Matrícula</th>
                                <th>Email</th>
                                <th class="td-actions"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @users.each do |user| %>
                                <tr>
                                    <td><%= user.name %></td>
                                    <td><%= user.cpf %></td>
                                    <td><%= user.matricula %></td>
                                    <td><%= user.email %></td>
                                    <td><a href="<%= user_path user%>" class="btn btn-sm btn-primary"%><i class="fa fa-eye" aria-hidden="true"></i> Ver</a>
                                        <% if is_admin? %>
                                            <a href="<%= delete_user_path user %>" class="btn btn-sm btn-danger", onclick="return confirm('Você tem certeza disso?');"><i class="fa fa-trash-o" aria-hidden="true"></i> Remover</a>
                                        <% end %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pull-right">
    <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
</div>
<br/>
<br/>
</div>

app/views/users/new.html.erb
<% @user.errors.each do |attr,message| %>
  <div style="padding-top: 50px;">
    <div class="alert alert-warning alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <%= message %>.
    </div>
  </div>
<%end%>
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Usuários</h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md- col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Cadastro de Usuário</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
           <%= form_for @user, url: {action: "create"}, html: {class: "form-horizontal form-label-left input_mask"} do |f| %>
          <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
              <%= f.label :name,"Nome Completo*"%>
              <%= f.text_field :name, class: 'form-control', placeholder: 'Nome e Sobrenome', minlength: '3', maxlength: '50', required: ''%>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12 form-group ">
              <%= f.label :dataNascimento,"Data Nascimento*"%>
              <%= f.date_field :dataNascimento, class: 'form-control', required: ''%>
            </div>
            <div class="col-md-3 col-sm-2 col-xs-12 form-group ">
              <%= f.label :cpf,"CPF*"%>
              <%= f.telephone_field :cpf, class: 'form-control', placeholder: 'Somente números', minlength: '11', maxlength: '11', required: ''%>
            </div>
          </div>
          <div class="row">
            <div class="col-md-3 col-sm-2 col-xs-12 form-group ">
              <%= f.label :matricula,"Matrícula*"%>
              <%= f.text_field :matricula, class: 'form-control', placeholder: 'Somente números', minlength: '9', maxlength: '9', required: ''%>
            </div>
          </div>
          <div class="row">
            <div class="col-md-3 col-sm-4 col-xs-12 form-group ">
              <%= f.label :telefone,"Telefone*"%>
              <%= f.telephone_field :telefone, class: 'form-control',placeholder: 'DDD + número', minlength: '11', maxlength: '11', required: ''%>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
              <%= f.label :email,"Email*"%>
              <%= f.email_field :email, class: 'form-control', required: ''%>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
              <%= f.label :email_confirmation,"Confirme o Email*"%>
              <%= f.email_field :email_confirmation, class: 'form-control', required: ''%>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12 form-group ">
              <%= f.label :cep,"CEP*"%>
              <%= f.telephone_field :cep, class: 'form-control',minlength: '8', maxlength: '8', required: ''%>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
              <%= f.label :endereco,"Endereço*"%>
              <%= f.text_field :endereco, class: 'form-control',minlength: '3', maxlength: '50', required: ''%>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12 form-group ">
              <%= f.label :numero,"Número*"%>
              <%= f.number_field :numero, class: 'form-control',placeholder: 'Somente números', required: ''%>
            </div>
            <div class="col-md-5 col-sm-5 col-xs-12 form-group ">
              <%= f.label :complemento,"Complemento"%>
              <%= f.text_field :complemento, class: 'form-control',maxlength: '20'%>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
              <%= f.label :password,"Senha*"%>
              <%= f.password_field :password, class: 'form-control',minlength: '6', maxlength: '15', required: ''%>
            </div>
            <div class="form-group col-md-4">
              <%= f.label :password_confirmation,"Confirme a Senha*"%>
              <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: 'off' , placeholder: 'Confirmação de senha', required: '', minlength: '6', maxlength: '15'%>
            </div>
          </div>
          <div class="ln_solid"></div>
          <div class="pull-right">
            <div class="btn-block">
              <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
              <button class="btn btn-primary" type="reset">Resetar</button>
              <%= f.submit "Enviar", class: 'btn btn-success'%>
            </div>
          </div>
          <% end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
  <% @user.errors.each do |attr,message| %>
  <div style="padding-top: 50px;">
    <div class="alert alert-warning alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <%= message %>.
  </div>
</div>
<%end%>
<div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Usuários</h3>
    </div>

</div>
<div class="clearfix"></div>
<div class="row">
  <div class="col-md- col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Perfil de Usuário</h2>
      <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <br />
    <div class="row">
      <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
        <p><strong>Nome</strong></p>
        <p><%= @user.name%></p>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
        <p><strong>Data Nascimento</strong></p>
        <p><%= @user.dataNascimento%></p>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
        <p><strong>CPF</strong></p>
        <p><%= @user.cpf%></p>
    </div>
</div>
<div class="row">
  <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
    <p><strong>Matrícula</strong></p>
    <p><%= @user.matricula%></p>
</div>
</div>
<div class="row">
  <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
    <p><strong>Telefone</strong></p>
    <p><%= @user.telefone%></p>
</div>
<div class="col-md-4 col-sm-4 col-xs-12 form-group ">
    <p><strong>Email</strong></p>
    <p><%= @user.email%></p>
</div>
</div>
<hr />
<div class="row">
   <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
      <p><strong>CEP</strong></p>
      <p><%= @user.cep%></p>
  </div>
</div>
<div class="row">
    <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
      <p><strong>Endereço</strong></p>
      <p><%= @user.endereco%></p>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
      <p><strong>Número</strong></p>
      <p><%= @user.numero%></p>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
      <p><strong>Complemento</strong></p>
      <p><%= @user.complemento%></p>
  </div>
</div>
</div>
</div>
</div>
</div>
<div id="actions" class="row">
  <div class="pull-right">
    <div class="col-md-12">
      <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-sm btn-default" %>
          <%if current_user == @user%>
          <a href="<%=edit_user_path @user %>" class="btn btn-sm btn-success"><i class="fa fa-pencil" aria-hidden="true" aria-hidden="true"></i> Editar</a>
          <%end%>
          <a href="<%= delete_user_path @user %>" class="btn btn-sm btn-danger", onclick="return confirm('Você tem certeza disso?');"><i class="fa fa-trash-o" aria-hidden="true"></i> Remover</a>
  </div>
</div>
</div>
</div>