config/routes.rb
Rails.application.routes.draw do
	root 'home#index'

	#user
	patch 'user/:id/edit/password'=> 'users#update_password', :as => 'alterar_senha'
	get 'users/:id/delete', to: 'users#destroy', :as => 'delete_user'
	get 'users' => 'users#index', :as => 'users'
	post 'users' => 'users#index', :as => 'users_post'
	post 'users/create' => 'users#create', :as => 'users_create'

	#sessions
	get    'login'   => 'sessions#new'
	post   'login'   => 'sessions#create'
	get 'logout', to: 'sessions#destroy', :as => 'logout'

	#books
	get 'books' => 'books#index', :as => 'books'
	post 'books' => 'books#index', :as => 'books_post'
	post 'books/create' => 'books#create', :as => 'books_create'
	get 'books/:id/delete', to: 'books#destroy', :as => 'delete_book'

	#loans
	get 'loans/create/:id' => 'loans#create', :as => 'loans_create'
	get 'loans/return_book/:id' => 'loans#return_book', :as => 'loans_return_book'
	get 'loans' => 'loans#index', :as => 'loans'

	#schedules
	get 'schedules/create/:id' => 'schedules#create', :as => 'schedules_create'
	get 'schedules' => 'schedules#index', :as => 'schedules'
	get 'schedule/:id/delete', to: 'schedules#destroy', :as => 'delete_schedule'


	resources :books, except:[:index, :create]
	resources :users, except:[:index, :create]
	resources :sessions
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	before_filter :autorized_user

	def new 
		@schedule = Schedule.new
		@book = Book.find(params[:id])
	end

	def create
		@book = Book.find_by_id(params[:id])
		if @book && !user_already_scheduled_book?(@book)
			@schedule = Schedule.new(book_id: @book.id, user_id: current_user.id)
			if scheduled?(@book.id)
				save_schedule('Agendamento criado, aguarde para saber o dia de pegar')
			else
				if @book.available
					@schedule.start_date = Time.zone.now + 1.day
					@schedule.end_date = @schedule.start_date + 15.days
					save_schedule('O agendamento foi criado e você deve pegá-lo até: ' + @schedule.start_date.to_s)
				else
					save_schedule('Agendamento criado, aguarde para saber o dia de pegar')
				end
			end
			UserNotifierMailer.send_email_to_scheduled(current_user, @schedule, @book).deliver_now
		else
			flash[:warning] = 'Não foi possível agendar o livro'
			redirect_to books_path
		end
	end

	def index
		@schedules = Schedule.where(user_id: current_user.id)
	end

	def destroy
		@schedule_dest = Schedule.find_by_id!(params[:id])
		if @schedule_dest && @schedule_dest.user_id == current_user.id
			book_id = @schedule_dest.book_id
			if @schedule_dest.destroy && book_id
				flash[:success] = 'Agendamento cancelado com sucesso'
				schedule = Schedule.find_by_book_id(book_id)
				if !schedule.nil? && schedule.start_date.nil? && schedule.end_date.nil?
					schedule.update_attributes(start_date: Time.zone.now + 1.day, end_date: Time.zone.now + 16.day)
				end
			else
				flash[:warning] = 'Não foi possível cancelar o agendamento'
			end
		end
		redirect_to schedules_path
	end

	private 
		def schedule_params
			params.require(:schedule)
		end

		def scheduled?(book_id)
			@schedule_valid = Schedule.find_by_book_id(book_id)
			!@schedule_valid.nil?
		end

		def save_schedule(msg)
			if @schedule.save
				redirect_to schedules_path
				flash[:success] = msg
			else
				redirect_to @book
				flash[:warning] = 'Não foi possível agendar o livro'
			end
		end
end

app/helpers/schedule_helper.rb
module ScheduleHelper
	def user_already_scheduled_book?(book)
		@schedule = Schedule.where(book_id: book, user_id: current_user.id).first
		!@schedule.nil?
	end
end

app/views/schedules/index.html.erb
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Meus Agendamentos</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md- col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <ul class="nav navbar-right panel_toolbox">
                                <h6 class="pull-right"><span class = "badge"><%=@schedules.count%></span></h6>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="dataTable_wrapper">
                        <table width="100%" class="table table-striped table-bordered table-hover table-responsive" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Data Limite Retirada</th>
                                    <th>Data Devolução (provável)</th>
                                    <th>Código de Barras (Livro)</th>
                                    <th>Título (Livro)</th>
                                    <th>Editora (Livro)</th>
                                    <th class="td-actions"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @schedules.each do |schedule| %>
                                <tr>
                                    <% if schedule.start_date == nil%>
                                        <td><i><strong>Aguarde Data</strong></i></td>
                                    <%else%>
                                        <td><%= schedule.start_date.strftime("%d/%m/%Y às %H:%M") %></td>
                                    <%end%>
                                    <% if schedule.end_date == nil%>
                                        <td><i><strong>Aguarde Data</strong></i></td>
                                    <%else%>
                                        <td><%= schedule.end_date.strftime("%d/%m/%Y às %H:%M") %></td>
                                    <%end%>
                                    <td><%= schedule.book.barcode%></td>
                                    <td><%= schedule.book.title%></td>
                                    <td><%= schedule.book.publisher%></td>
                                    <td width="10"><a href="<%= delete_schedule_path schedule%>" class="btn btn-sm btn-primary"%><i class="fa fa-eraser" aria-hidden="true"></i> Cancelar</a></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                    <br>
                </div>
            </div>
        </div>
    </div>
    <div class="pull-right">
        <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
    </div>
    <br/>
    <br/>
</div>