config/routes.rb
Rails.application.routes.draw do
	root 'home#index'

	#user
	patch 'user/:id/edit/password'=> 'users#update_password', :as => 'alterar_senha'
	get 'users/:id/delete', to: 'users#destroy', :as => 'delete_user'
	get 'users' => 'users#index', :as => 'users'
	post 'users' => 'users#index', :as => 'users_post'
	post 'users/create' => 'users#create', :as => 'users_create'

	#sessions
	get    'login'   => 'sessions#new'
	post   'login'   => 'sessions#create'
	get 'logout', to: 'sessions#destroy', :as => 'logout'

	#books
	get 'books' => 'books#index', :as => 'books'
	post 'books' => 'books#index', :as => 'books_post'
	post 'books/create' => 'books#create', :as => 'books_create'
	get 'books/:id/delete', to: 'books#destroy', :as => 'delete_book'

	#loans
	get 'loans/create/:id' => 'loans#create', :as => 'loans_create'
	get 'loans/return_book/:id' => 'loans#return_book', :as => 'loans_return_book'
	get 'loans' => 'loans#index', :as => 'loans'

	#schedules
	get 'schedules/create/:id' => 'schedules#create', :as => 'schedules_create'
	get 'schedules' => 'schedules#index', :as => 'schedules'
	get 'schedule/:id/delete', to: 'schedules#destroy', :as => 'delete_schedule'


	resources :books, except:[:index, :create]
	resources :users, except:[:index, :create]
	resources :sessions
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :schedules, :dependent => :destroy
	has_one :loan
	has_one :case
	belongs_to :case
	#title
	validates_length_of :title,
						:within => 1..100, 
						:too_short => "Título tem que ter no mínimo 1 caracter",
				  		:too_long => "Título tem que ter no máximo 100 caracteres"
	validates :title, :presence => { :message => "Informe o título do livro" }
	
	#subtitle
	validates :subtitle, length: { maximum: 100, message: "Subtítulo tem que ter no máximo 100 caracteres"}

	#author_one
	validates_length_of :author_one,
						:within => 3..100, 
						:too_short => "Primeiro autor tem que ter no mínimo 3 caracteres",
				  		:too_long => "Primeiro autor tem que ter no máximo 100 caracteres"
	validates :author_one, :presence => { :message => "Informe o nome do primeiro autor"}
	
	
	#author_two
	validates :author_two, length: { maximum: 100, message: "Segundo autor tem que ter no máximo 100 caracteres"}

	#author_three
	validates :author_three, length: { maximum: 100, message: "Terceiro autor tem que ter no máximo 100 caracteres"}

	#publisher
	validates_length_of :publisher,
						:within => 2..20, 
						:too_short => "Editora tem que ter no mínimo 2 caracteres",
				  		:too_long => "Editora tem que ter no máximo 20 caracteres"
	validates :publisher, :presence => { :message => "Informe a editora do livro"}

	#year
	validates_length_of :year,
						:within => 4..4, 
						:too_short => "Ano tem que ter no mínimo 4 caracteres",
				  		:too_long => "Ano tem que ter no máximo 4 caracteres"
	validates :year, :presence => {:message => "Informe o ano do livro"}
	
	#city
	validates_length_of :city,
						:within => 3..20, 
						:too_short => "Cidade tem que ter no mínimo 3 caracteres",
				  		:too_long => "Cidade tem que ter no máximo 20 caracteres"
	validates :city, :presence => { :message => "Informe o local do livro"}
	

	#edition
	validates_length_of :edition,
						:within => 1..3, 
						:too_short => "Edição tem que ter no mínimo 1 caracter",
				  		:too_long => "Edição tem que ter no máximo 3 caracteres"
	validates :edition, :presence => { :message => "Informe a edição do livro"}

	#volume
	validates :volume, length: { maximum: 3, message: "Volume tem que ter no máximo 3 caracteres"}

	#pages
	validates_length_of :pages,
						:within => 1..5, 
						:too_short => "Página tem que ter no mínimo 1 caracteres",
				  		:too_long => "Página tem que ter no máximo 5 caracteres"
	validates :pages, :presence => { :message => "Informe as páginas do livro"}

	#isbn
	validates_length_of :ISBN,
						:within => 1..13, 
						:too_short => "ISBN tem que ter no mínimo 1 caracteres",
				  		:too_long => "ISBN tem que ter no máximo 13 caracteres"
	validates :ISBN, :presence => {:message => "Informe o ISBN do livro" }

	#barcode
	validates_length_of :barcode,
						:within => 1..15, 
						:too_short => "Código de barras tem que ter no mínimo 1 caracteres",
				  		:too_long => "Código de barras tem que ter no máximo 15 caracteres"
	validates :barcode, :presence => { :message => "Informe o código de barras do livro"}
	
	include PgSearch
	pg_search_scope :search_full_text, 
	                :against => [:title, :author_one, :publisher], 
	                :using => { 
	                	:tsearch => {:prefix => true, :any_word => true}
	                    }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_filter :autorized_user
	before_action :set_book, only: [:show, :edit, :update, :destroy]
	helper_method :is_admin?

	def index
		search_book(params[:book_search])
		@book_search = params[:book_search]
	end

	def new
		if is_admin?
			@book = Book.new
		else
			redirect_to books_path
			flash[:warning] = "Você não pode acessar essa página"
		end
	end

	def create
		if is_admin? 
			@book = Book.new(book_params)
			@book.available = true
			case_book = Case.find_by(book_id: nil)
			if !case_book.nil? && enough_cases?
				@book.case_id = case_book.id
				if @book.save
					case_book.update_attribute(:book_id, @book.id)
					flash[:success] = "Livro criado com sucesso"
					redirect_to books_path
				else
				   render :new
				end
			else
				flash[:warning] = "Não foi possível criar o livro, pois não existe uma case disponível."
			end
		else
			redirect_to books_path
			flash[:warning] = "Você não pode realizar essa ação"
		end
	end

	def show
		unless @book.condition_deactivate 
			@schedules = @book.schedules
		else
			redirect_to books_path
		end
	end

	def edit
		if is_admin? && !@book.condition_deactivate
			@selected_year = @book.year
		else
			redirect_to books_path
			flash[:warning] = "Você não pode acessar essa página"
		end
	end
	
	def update
		if is_admin? && !@book.condition_deactivate
			if @book.update(book_params)
				flash[:success] = "Livro atualizado com sucesso"
				redirect_to books_path
			else
				render :edit
			end
		else
			redirect_to books_path
			flash[:warning] = "Você não pode realizar essa ação"
		end
	end

	def destroy
		if is_admin?
			@book = Book.find(params[:id])
	   		if @book.present?
	   			case_book = Case.find(@book.case_id)
	   			if !case_book.nil?
	   				case_book.update_attribute(:book_id, nil)
	   			end
      		@book.update_attribute(:condition_deactivate, true)
      		@book.update_attribute(:case_id, nil)
      		flash[:success] = "Livro apagado com sucesso"
				redirect_to books_url
	    	end
	    else
			redirect_to books_path
			flash[:warning] = "Você não pode realizar essa ação"
		end
	end

	private 
	def set_book
		@book = Book.find(params[:id])
	end

	def book_params
		params.require(:book).permit(:author_one, :author_two, :author_three, :title,
		 :subtitle, :publisher, :year, :city, :edition, :volume, :pages, :ISBN, :barcode)
	end

	def search_book(book_search)
		if !book_search.blank?
			@books = Book.where(condition_deactivate: false).search_full_text("#{book_search}")
		else
			@books = Book.where(condition_deactivate: false)
		end
	end

	def enough_cases?
		cases_count = Case.all.count
		books_count = Book.all.count

		if books_count >= cases_count
			false
		else
			true
		end
	end
end

app/views/books/edit.html.erb
  <% if is_admin? %>
  <% @book.errors.each do |attr,message| %>
    <div style="padding-top: 50px;">
      <div class="alert alert-warning alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <%= message %>.
      </div>
    </div>
  <%end%>
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Livros</h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md- col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Editar Livros</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            <%= form_for @book, html:{class:"form-horizontal form-label-left input_mask"} do | f | %>
             <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :title,"Título*"%>
                <%= f.text_field :title, class: 'form-control', placeholder: 'Título do Livro',minlength: '1', maxlength: '100', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :subtitle,"Subtítulo"%>
                <%= f.text_field :subtitle, class: 'form-control', placeholder: 'Subtítulo do Livro', maxlength: '100'%>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :author_one,"Primeiro Autor*"%>
                <%= f.text_field :author_one, class: 'form-control', placeholder: 'Primeiro Autor', minlength: '3', maxlength: '100', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :author_two,"Segundo autor"%>
                <%= f.text_field :author_two, class: 'form-control', placeholder: 'Segundo Autor', maxlength: '100'%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :author_three,"Terceiro Autor"%>
                <%= f.text_field :author_three, class: 'form-control', placeholder: 'Terceiro Autor', maxlength: '100'%>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :publisher,"Editora*"%>
                <%= f.text_field :publisher, class: 'form-control', placeholder: 'Editora',minlength: '2', maxlength: '20', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :year,"Ano*"%>
                <%= select_year @selected_year, { :start_year => Time.zone.now.year+1, 
                                                      :end_year => Time.zone.now.year - 500, 
                                                      :field_name => :year, 
                                                      :prefix => :book}, 
                                                      class:"form-control", required: true%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :city, "Local*"%>
                <%= f.text_field :city, class: 'form-control', placeholder: 'Local', minlength: '3', maxlength: '20', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :edition,"Edição*"%>
                <%= f.number_field :edition, class: 'form-control',minlength: '1', maxlength: '4', placeholder: 'Edição', minlength: '1', maxlength: '3',  required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :volume,"Volume"%>
                <%= f.number_field :volume, class: 'form-control', placeholder: 'Volume', minlength: '0', maxlength: '3'%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :pages,"Páginas*"%>
                <%= f.number_field :pages, class: 'form-control', placeholder: 'Páginas', minlength: '1', maxlength: '5', required: ''%>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :ISBN, "ISBN*"%>
                <%= f.text_field :ISBN, class: 'form-control', placeholder: 'ISBN', minlength: '1', maxlength: '13', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :barcode, "Código de Barras*"%>
                <%= f.text_field :barcode, class: 'form-control', placeholder: 'Código de Barras', minlength: '1', maxlength: '15', required: ''%>
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="pull-right">
              <div class="btn-block">
                <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
                <button class="btn btn-primary" type="reset">Resetar</button>
                <%= f.submit "Enviar", class: 'btn btn-success'%>
              </div>
            </div>
            <% end%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%else%>
    <div class="title_left">
      <h3>Você não pode acessar essa página!</h3>
    </div>
    <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
  <%end%>

app/views/books/index.html.erb
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Livros</h3>
        </div>
    </div>
    <%= form_tag books_post_path, method: :post do %>
    <div class="title_right">
        <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <%= text_field_tag :book_search, @book_search, class: "form-control input-md", placeholder: "Título, Autor, Editora..."%>
                <span class="input-group-btn">
                <button class="btn btn-default" type="submit"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                </span>
            </div>
        </div>
    </div>
    <%end%>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md- col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Consulta de Livro</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <h6 class="pull-right"><span class = "badge"><%=@books.count%></span></h6>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <table width="100%" class="table table-striped table-bordered table-hover table-responsive" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>Disponibilidade</th>
                            <th width="25%">Título</th>
                            <th>Primeiro Autor</th>
                            <th>Editora</th>
                            <th>Ano</th>
                            <th>Edição</th>
                            <th class="td-actions"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @books.each do |book| %>
                        <tr>
                            <td><%if !book.available ||  book.schedules.size > 0%>
                                <i class="fa fa-times-circle" aria-hidden="true" style="color:red;"></i>
                            <%else%>
                                <i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>
                            <%end%></td>
                            <td><%= book.title %></td>
                            <td><%= book.author_one %></td>
                            <td><%= book.publisher %></td>
                            <td><%= book.year %></td>
                            <td><%= book.edition %></td>
                            <td><a href="<%= book_path book%>" class="btn btn-sm btn-primary"%><i class="fa fa-eye" aria-hidden="true"></i> Ver</a>
                                <% if is_admin? %>
                                <a href="<%=edit_book_path book %>" class="btn btn-sm btn-success"><i class="fa fa-pencil" aria-hidden="true"></i> Editar</a>
                                <a href="<%= delete_book_path book %>" class="btn btn-sm btn-danger", onclick="return confirm('Você tem certeza disso?');"><i class="fa fa-trash-o" aria-hidden="true"></i> Remover</a>
                            </td>
                            <% end %>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>
</div>
<div class="pull-right">
    <% if is_admin? %>
    <a href="<%= new_book_path %>" class="btn btn-success"><i class="fa fa-plus-square" aria-hidden="true"></i> Cadastrar livro</a>
    <% end %>
</div>
<br/>
<br/>
</div>

app/views/books/new.html.erb
<% if is_admin? %>
  <% @book.errors.each do |attr,message| %>
    <div style="padding-top: 50px;">
      <div class="alert alert-warning alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <%= message %>.
      </div>
    </div>
  <%end%>
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Livros</h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md- col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Cadastro de Livros</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            <%= form_for @book, url: {action: "create"}, html: {class: "form-horizontal form-label-left input_mask"} do |f| %>
            <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :title,"Título*"%>
                <%= f.text_field :title, class: 'form-control', placeholder: 'Título do Livro',minlength: '1', maxlength: '100', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :subtitle,"Subtítulo"%>
                <%= f.text_field :subtitle, class: 'form-control', placeholder: 'Subtítulo do Livro', maxlength: '100'%>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :author_one,"Primeiro Autor*"%>
                <%= f.text_field :author_one, class: 'form-control', placeholder: 'Primeiro Autor', minlength: '3', maxlength: '100', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :author_two,"Segundo autor"%>
                <%= f.text_field :author_two, class: 'form-control', placeholder: 'Segundo Autor', maxlength: '100'%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :author_three,"Terceiro Autor"%>
                <%= f.text_field :author_three, class: 'form-control', placeholder: 'Terceiro Autor', maxlength: '100'%>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :publisher,"Editora*"%>
                <%= f.text_field :publisher, class: 'form-control', placeholder: 'Editora',minlength: '2', maxlength: '20', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :year,"Ano*"%>
                <%= select_year Time.zone.now.year, { :start_year => Time.zone.now.year+1, 
                                            :end_year => Time.zone.now.year - 500, 
                                            :field_name => :year, 
                                            :prefix => :book}, 
                                            class:"form-control", required: true%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :city, "Local*"%>
                <%= f.text_field :city, class: 'form-control', placeholder: 'Local', minlength: '3', maxlength: '20', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :edition,"Edição*"%>
                <%= f.number_field :edition, class: 'form-control',minlength: '1', maxlength: '4', placeholder: 'Edição', minlength: '1', maxlength: '3',  required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :volume,"Volume"%>
                <%= f.number_field :volume, class: 'form-control', placeholder: 'Volume', maxlength: '3'%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :pages,"Páginas*"%>
                <%= f.number_field :pages, class: 'form-control', placeholder: 'Páginas', minlength: '1', maxlength: '5', required: ''%>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :ISBN, "ISBN*"%>
                <%= f.text_field :ISBN, class: 'form-control', placeholder: 'ISBN', minlength: '1', maxlength: '13', required: ''%>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                <%= f.label :barcode, "Código de Barras*"%>
                <%= f.text_field :barcode, class: 'form-control', placeholder: 'Código de Barras', minlength: '1', maxlength: '15', required: ''%>
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="pull-right">
              <div class="btn-block">
                <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
                <button class="btn btn-primary" type="reset">Resetar</button>
                <%= f.submit "Enviar", class: 'btn btn-success'%>
              </div>
            </div>
            <% end%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%else%>
    <div class="title_left">
      <h3>Você não pode acessar essa página!</h3>
    </div>
    <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-md btn-default" %>
  <%end%>

app/views/books/show.html.erb
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Livros</h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md- col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Consulta de Livro</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <div class="row">
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Disponibilidade</strong></p>
                            <p>
                                <%if !@book.available || @book.schedules.size > 0%>
                                <i class="fa fa-times-circle" aria-hidden="true" style="color:red;"></i>
                                <%else %>
                                <i class="fa fa-check-circle" aria-hidden="true" style="color:green;"></i>
                                <%end%>
                            </p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Título</strong></p>
                            <p><%= @book.title%></p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Subtítulo</strong></p>
                            <p><%= @book.subtitle%></p>
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Primeiro Autor</strong></p>
                            <p><%= @book.author_one%></p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Segundo Autor</strong></p>
                            <p><%= @book.author_two%></p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Terceiro Autor</strong></p>
                            <p><%= @book.author_three%></p>
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Editora</strong></p>
                            <p><%= @book.publisher%></p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Ano</strong></p>
                            <p><%= @book.year%></p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Local</strong></p>
                            <p><%= @book.city%></p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Edição</strong></p>
                            <p><%= @book.edition%></p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Volume</strong></p>
                            <p><%= @book.volume%></p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Páginas</strong></p>
                            <p><%= @book.pages%></p>
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>ISBN</strong></p>
                            <p><%= @book.ISBN%></p>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-12 form-group ">
                            <p><strong>Código de Barras</strong></p>
                            <p><%= @book.barcode%></p>
                        </div>
                    </div>
                </div>
                <div id="actions" class="row">
                    <div class="pull-right">
                        <div class="col-md-12">
                            <%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Voltar</a>'.html_safe, :back, class: "btn btn-sm btn-default" %>
                            <% if is_admin? %>
                            <a href="<%=edit_book_path @book %>" class="btn btn-sm btn-success"><i class="fa fa-pencil" aria-hidden="true" aria-hidden="true"></i> Editar</a>
                            <a href="<%=delete_book_path @book %>" class="btn btn-sm btn-danger", onclick="return confirm('Você tem certeza disso?');"><i class="fa fa-trash-o" aria-hidden="true"></i> Remover</a>
                            <% else %>
                            <%unless user_already_scheduled_book?(@book) || current_user_loaned?(@book)%>
                            <a href="<%=schedules_create_path @book%>" class="btn btn-sm btn-primary"><i class="fa fa-calendar" aria-hidden="true"></i> Agendar Empréstimo</a>
                            <%else%>
                            <a href="<%=schedules_create_path @book%>" class="btn btn-sm btn-default disabled" disabled="true"><i class="fa fa-calendar" aria-hidden="true"></i> Agendar Empréstimo</a>
                            <%end%>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="x_panel">
    <div class="x_title">
        <h2>Próximo Agendamento para este livro</h2>
        <ul class="nav navbar-right panel_toolbox">
            <h6 class="pull-right"><span class = "badge" style="color: white;">Total de Agendamentos: <%=@schedules.count%></span></h6>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="dataTable_wrapper">
        <table width="100%" class="table table-striped table-bordered table-hover table-responsive" id="dataTables-example">
            <thead>
                <tr>
                    <th width="50%">Data Início (provável)</th>
                    <th width="50%">Data Devolução (provável)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <% @schedules.limit(1).each do |schedule| %>
                    <td><%= schedule.start_date %></td>
                    <td><%= schedule.end_date %></td>
                    <%end%>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</div>